[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.pnpm"]

[phases.install]
cmds = [
  "cd ../.. && pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "cd ../.. && pnpm --filter @public-auditor/api build"
]

[start]
cmd = "node dist/server.js"
